<?php return array (
    'menus' => false,
    'links' => false,
    'pages' => false,
    'articles' => false,
    'pictures' => false,
    'videos' => false,
    'files' => false,
    'projects' => false,
    'profiles' => false,
    'profile_picture' => ['w'=>3,'h'=>4],
    'sermons' => false,
    'events' => false,
    'packages' => false,
    'products' => false,
    'branches' => false,
    'contact' => NULL,
    'content_css' => NULL,
    'menu' =>
        array (
            'admin-articles' => 'Articles',
            'admin-pictures' => 'Pictures',
            'admin-videos' => 'Videos',
            'admin-files' => 'Files',
            'admin-projects' => 'Projects',
            'admin-profiles' => 'Profiles',
            'admin-sermons' => 'Sermons',
            'admin-events' => 'Events',
            'admin-packages' => 'Packages',
            'admin-products' => 'Products',
        ),
);
